# Generated by Django 5.1.6 on 2025-07-02 14:39

import django.core.validators
import manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identifikator')),
            ],
            options={
                'verbose_name': 'Janr ',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identifikator')),
                ('country', models.CharField(max_length=50, verbose_name='Davlati')),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili')),
                ('language', models.CharField(choices=[('uz', "O'zbek tilida"), ('ru', 'Rus tilida'), ('en', 'Ingiliz tilida')], max_length=10, verbose_name='Tili')),
                ('duration', models.CharField(default='1 soat', max_length=10, verbose_name='Davomiyligi')),
                ('age', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('16+', '16+'), ('18+', '18+'), ('21+', '21+')], max_length=3, verbose_name='Yosh chegarasi')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Surati')),
                ('video', models.FileField(upload_to='video/', validators=[manager.validators.validate_video_file_extension], verbose_name='Videosi')),
                ('genre', models.ManyToManyField(related_name='genre', to='manager.genres', verbose_name='Janr')),
            ],
            options={
                'verbose_name': 'Kino ',
                'verbose_name_plural': 'Kinolar',
            },
        ),
    ]
