# Generated by Django 5.1.6 on 2025-07-03 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_movies_duration_alter_movies_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili'),
        ),
    ]
