# Generated by Django 5.1.6 on 2025-07-03 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_movies_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-id'], 'verbose_name': 'Kino ', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili'),
        ),
    ]
